# Site wide configuration

title: "ARTURO GUZMÁN SOLERA "
description: "Aquí podrás encontrar todos mis proyectos"
logo: foto-carnet.jpg
teaser: foto-carnet.jpg
locale: en_US
url: "https://arturogzm93.github.io/portfolio/"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Arturo Guzmán"
  web: 
  twitter: 
  bio: 
  avatar: "foto-carnet.jpg" # 160x160 px image for author byline
  google:
    plus: "+MichaelRoseDesign"
    ad-client: "ca-pub-7328585512091257"
    ad-slot: 3049671934
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
